services:
  - type: web
    name: odf-app
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: odf_user
      - key: DB_PASSWORD
        value: Dinuka@2001
      - key: DB_NAME
        value: odf_manager
